services:
  - type: web
    name: school-app
    runtime: docker
    envVars:
      - key: ENV
        value: "production"
      - key: DEBUG
        value: "False"
      - key: SITE_URL
        value: "https://school-reports.onrender.com"
      - key: ALLOWED_HOSTS
        value: "school-7lgm.onrender.com,school-reports.onrender.com"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: school-redis
          property: connectionString
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

  - type: worker
    name: school-worker
    runtime: docker
    startCommand: "celery -A config worker --loglevel=info"
    envVars:
      - key: ENV
        value: "production"
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: school-redis
          property: connectionString
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

  - type: redis
    name: school-redis
    ipAllowList: [] # Only allow internal connections
    plan: free # Or starter
