services:
  - type: web
    name: school-app
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn config.wsgi:application --log-file -"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: "postgresql://school_db_lbxv_user:KoIAnrjvXRU8oATuw6DDqNJajUXd5xw4@dpg-d50rlgtactks73bjebi0-a/school_db_lbxv"
      - key: CLOUDINARY_CLOUD_NAME
        value: "dnob4uzo6"
      - key: CLOUDINARY_API_KEY
        value: "338112422428927"
      - key: CLOUDINARY_API_SECRET
        value: "cbvBfgbgfnlDA69i7xG11KJ_da8"
